### PR TITLE
update readme file

### PR DESCRIPTION
**Pull request by ringtho**
Please checkout my readme. Please feel free to incase of any issues. Thanks
 @ringtho @KapsonLabs @MukuruH @bakersen @Kyeza @nadralia @Kwandera @JammyKalungi @reifred @ernesthenry @jennizalwango @jkMugabe @richien @Araali1 @Mastula77 @Genza999 @Wabuluka @vicentbaiga @noahkalyesubula @LynetteMK @joekirumira @bashirdeveloper @lizz24 @kalsmic @erioc @mwes23 @NANKYAPHIONA @HarunaIbnYusuf @k7ko @v1b3m @KengoWada

### CODE REVIEW

**Comment by kalsmic** [comment]
@ringtho, SO far so good but you also need to add a description of how one can set up and try out the project, also add one on how can run the tests.

**Comment by ringtho** [comment]
> @ringtho, SO far so good but you also need to add a description of how one can set up and try out the project, also add one on how can run the tests.

@kalsmic i had provided the description to set up the project and run it in the installation instructions

**Comment by kalsmic** [comment]
> > @ringtho, SO far so good but you also need to add a description of how one can set up and try out the project, also add one on how can run the tests.
> 
> @kalsmic i had provided the description to set up the project and run it in the installation instructions

Sorry I think I check a preview for a wrong branch, I have confirmed it;s actually there. Looks good. Sorry about the confusion.

**Comment by ringtho** [comment]
> > > @ringtho, SO far so good but you also need to add a description of how one can set up and try out the project, also add one on how can run the tests.
> > 
> > 
> > @kalsmic i had provided the description to set up the project and run it in the installation instructions
> 
> Sorry I think I check a preview for a wrong branch, I have confirmed it;s actually there. Looks good. Sorry about the confusion.

Thanks Arthur

**Comment by v1b3m** [comment]
Looks great to me.
Great work.

**Pull request merged**
